version: 0.0
os: linux
files:
  - source: .next
    destination: /var/www/docbooker
file_exists_behavior: OVERWRITE
hooks:
  ApplicationStart:
    - location: scripts/start_application.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_application.sh
      timeout: 300
      runas: root
